import 'package:flutter/material.dart';
import 'package:hexcolor/hexcolor.dart';

Color myColor = HexColor('#353448');
Color suvaGreyColor = HexColor('#8d8d8d');
Color customOrangeColor = HexColor('#ce9654');
Color silverColor = HexColor('#b9b9b9');
Color formFieldColor = HexColor('#F9F9F9');
Color formFieldBorderColor = HexColor('#F2F2F2');
Color formFieldActiveBorderColor = HexColor('#004682');
Color formFieldErrorBorderColor = HexColor('#FF0023');
Color formFieldTextFillColor = HexColor('#004A80');
Color formFieldTextErrorColor = HexColor('#EA3F3F');
Color formFieldTextCorrectColor = HexColor('#0096AB');
Color pinBorderCompleteColor = HexColor('#6F6BB2');
Color elevationColor = HexColor('#00000029');
Color containerColor = HexColor('#EAEAEA');
Color containerTextColor = HexColor('#515151');
Color notificationsTimeColor = HexColor('#989898');
Color notificationBorderColor = HexColor('#EDEDED80');
Color dragImageColor = HexColor('#707070');
Color sortingContainerColor = HexColor('#FDFDFD');
Color analystsContainerColor = HexColor('#D1D1D11A');
Color followButtonColor = HexColor('#6F6BB2');
Color customBlue = HexColor('#6F6BB2');
Color smallContainerColor = HexColor('#FBFBFB');
Color profileAppbarColors = HexColor('#6f6bb2').withOpacity(0.1);
